import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  customFigma: {
    flex: 1,
    backgroundColor: '#FCE5EB',
    position: 'relative',
  },
  headerViu: {
    flexDirection: 'row',
    marginTop: 54,
    marginHorizontal: 33,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textHeader: {
    marginLeft: 5.5,
    fontFamily: 'Nunito-VariableFont_wght',
    fontWeight: 700,
    fontSize: 24,
    lineHeight: 33,
    color: '#E45C81',
  },
  imageTiTle: {
    width: 50,
    height: 40,
  },
  modal: {
    marginHorizontal: 32,
    height: 287,
    backgroundColor: '#fff',
    borderRadius: 24,
    marginTop: 52,
    alignItems: 'center',
    zIndex: 100,
  },
  modalText: {
    color: '#3B394A',
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 32,
  },
  inputViu: {
    height: 48,
    width: 263,
    backgroundColor: '#F6F6F8',
    borderRadius: 12,
    marginTop: 16,
    paddingLeft: 36,
  },
  buttonModal: {
    marginTop: 16,
    backgroundColor: '#3952D5',
    width: 263,
    height: 47,
  },
  imageViu: {
    width: 337,
    height: 302,
    resizeMode: 'cover',
    position: 'relative',
  },
  imageBottom: {alignItems: 'center', bottom: 40},
  upModal: {
    width: 144,
    height: 115,
    borderRadius: 100,
    backgroundColor: '#FCE5EB',
    position: 'absolute',
    top: 60,
    // left: 55,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textup: {
    textAlign: 'center',
    color: '#0A528A',
    fontFamily: 'DancingScript-Bold',
  },
  iconInput1: {
    position: 'absolute',
    top: 85,
    zIndex: 1,
  },
  iconInput2: {
    position: 'absolute',
    top: 150,
    zIndex: 1,
  },
  visitContainer: {
    backgroundColor: '#E7EBF7',
    alignItems: 'center',
  },
  visitHeader: {
    marginTop: 66,
    backgroundColor: '#ffff',
    width: 311,
    height: 71,
    borderRadius: 32,
    paddingHorizontal: 22,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  textVisit1: {
    color: '#3B394A',
    fontSize: 20,
  },
  textVisit2: {
    color: '#3B394A',
    fontSize: 16,
  },
  visitContent: {
    backgroundColor: '#ffff',
    marginTop: 11,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    width: '100%',
    overflow: 'hidden',
  },
  textVisit: {
    textAlign: 'center',
    marginTop: 24,
  },
  imageVisit: {
    width: 74,
    height: 74,
    marginRight: 13,
    marginLeft: 16,
    resizeMode: 'cover',
  },
  contents: {
    flexDirection: 'row',
  },
  buttons: {
    marginTop: 6,
    width: 44,
    height: 23,
    backgroundColor: '#F7C0CF',
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 6,
  },
  buttonsXanh: {
    marginTop: 6,
    width: 44,
    height: 23,
    backgroundColor: '#C4CEEC',
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 6,
  },
});
export default styles;
